name: Send a slack message
on: [push]
jobs:
  bigChiefAutobot:
    runs-on: ubuntu-latest
    steps:
      - uses: 8398a7/action-slack@v3
        with: 
          status: ${{ job.status }}
          fields: repo,message,commit,author
        env: 
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}