name: Change Package.json
on: [push]

jobs:
  notifier:
    runs-on: ubuntu-latest
    steps:
      - uses: 8398a7/action-slack@v3
        with:
          status: custom
          text: "<!channel>"
          fields: workflow,job,commit,repo,ref,author,took
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_NOTIFIER }}