name: Change Package.json
on:
  push:
    branches:
      - develop
    paths:
      - 'package.json'

jobs:
  notifier:
    runs-on: ubuntu-latest
    steps:
      - uses: 8398a7/action-slack@v3
        with:
          status: custom
          text: "<!channel>"
          fields: job
          custom_payload: |
          {
            attachments: [{
              color: '%{{ job.status }}' === 'success' ? 'good' : '${{ job.status }} === 'failure' ? 'danger' : 'warning',
              text: `Change in package.json in commit(${process.env.AS_COMMIT}) of ${process.env.AS_REPO} by ${process.env.AS_AUTHOR} ${{ job.status }} in ${process.env.AS_TOOK}`
            }]
          }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_NOTIFIER }}