name: On Path event
on:
  push:
    paths:
      - 'main.py'
jobs:
  bigChiefAutobot:
    runs-on: ubuntu-latest
    steps:
      - uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          text: "Modificaste o arquivo main.py @here"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}